---
abstract: 'Elluminate Live (c) SAS (v2) SDK bindings'
author:
  - 'David Warring <david.warring@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Builder: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Elive::Sas
name: Elive-Sas
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  Date::Parse: 0
  Elive: 0.73
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 2.35
  Mouse: 0.56
  Pod::Usage: 0
  URI: 0
  XML::Simple: 0
  YAML: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
