---
abstract: 'Perl bindings for the Elluminate Live Standard Bridge (V2) [TRIAL]'
author:
  - 'David Warring <david.warring@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.56
  Test::Builder: 0
  Test::Fatal: 0
  Test::More: 0
  Test::Warn: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Elive::StandardV3
name: Elive-StandardV3
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  Date::Parse: 0
  Elive::DAO: 0.06
  Elive::Util: 0.01
  File::Basename: 0
  File::Spec: 0
  Mouse: 0.56
  SOAP::Lite: 0.712
  Try::Tiny: 0
  URI: 0
  XML::Simple: 0
  YAML::Syck: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: https://dwarring@elive.svn.sourceforge.net/svnroot/elive/trunk/Elive-StandardV3
version: 0.00_1
