---
abstract: 'Perl bindings for the Elluminate Live Standard Bridge (V2) [TRIAL]'
author:
  - 'David Warring <david.warring@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Builder: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Elive::StandardV2
name: Elive-StandardV2
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  Date::Parse: 0
  Elive: 1.05
  File::Basename: 0
  File::Spec: 0
  Mouse: 0.56
  SOAP::Lite: 0.712
  Try::Tiny: 0
  URI: 0
  XML::Simple: 0
  YAML: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: https://elive.svn.sourceforge.net/svnroot/elive/trunk/Elive-StandardV2
version: 0.01_4
