---
abstract: 'Perl binds for the Elluminate Live (c) Standard Bridge V2 API'
author:
  - 'David Warring <david.warring@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Builder: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Elive::StandardV2
name: Elive-StandardV2
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  Date::Parse: 0
  Elive: 0.75
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 2.35
  Mouse: 0.56
  Pod::Usage: 0
  URI: 0
  XML::Simple: 0
  YAML: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
  repository: https://dwarring@elive.svn.sourceforge.net/svnroot/elive/trunk/Elive-StandardV2
version: 0.00_1
