---
abstract: 'Elluminate Live (c) SDK bindings'
author:
  - 'David Warring <david.warring@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Builder: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Elive
name: Elive
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  Date::Parse: 0
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 2.35
  HTML::Entities: 0
  IO::Interactive: 0
  IO::Prompt: 0
  MIME::Base64: 0
  MIME::Types: 0
  Mouse: 0.29
  Pod::Usage: 0
  SOAP::Lite: 0.712
  Scalar::Util: 0
  Storable: 0
  Term::ReadKey: 0
  Term::ReadLine: 0
  Term::ReadLine::Perl: 0
  Time::Local: 0
  URI: 0
  URI::Escape: 0
  XML::Simple: 0
  YAML: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
  repository: https://elive.svn.sourceforge.net/svnroot/elive/trunk/Elive
version: 0.74
